# Change baseurl before deploy
baseurl = "https://xiuuuuuuuuuu.github.io/Personal-Blog/"
locale  = "zh-cn"
title   = "Xiuuuuuuuuuu"
hasCJKLanguage = true
 theme = "stack"
defaultContentLanguage = "zh-cn"
 # disqusShortname = "hugo-theme-stack"
resourceDir = "C:/Users/Administrator/AppData/Local/Temp/hugo-resources"

[pagination]
    pagerSize = 5
